# 工作流名称
name: Sync-Images-from-DockerHub-to-Coding
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images from DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1


    - name: Login to Coding
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.CODING_ADDRESS }}
        username: ${{ secrets.CODING_USER }}
        password: ${{ secrets.CODING_TOKEN }}
        logout: false


    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://lengyue233/fish-speech:v1.1.2 docker://g-vduf6304-docker.pkg.coding.net/test/new/fish-speech:v1.1.2
